#!/usr/bin/env python3
"""
make_all_figs.py - one-shot generator for all matplotlib data figures.

Merges the 16 individual plotting scripts into a single entry point. Each original
script is invoked as an isolated section (via runpy) so their module-level plotting
code executes and writes its PNG/PDF outputs, exactly as when run standalone.

Usage:
    python make_all_figs.py              # generate all figures
    python make_all_figs.py --list       # list figure sections
    python make_all_figs.py --only ablation_bars token_efficiency   # subset

Outputs land next to each script (figures/ and figures_v22/ and figures_supp/),
matching the paths referenced by latex/main.tex.

README assets are stored under ../assets and are generated separately.
"""
import argparse, os, runpy, sys, traceback

HERE = os.path.dirname(os.path.abspath(__file__))

# (section_name, relative_script_path, short_description)
FIGS = [
    ("fig1_scaling",        "latex/figures/fig1_code.py",              "Fig 1: 6-tier scaling trajectory (Overall vs memory size)"),
    ("fig2_baselines",      "latex/figures/fig2_code.py",              "Fig 2: HDM routing tradeoff / baselines"),
    ("fig3_hdm_routing",    "latex/figures/fig3_code.py",              "Fig 3: HDM routing"),
    ("ablation_bars",       "latex/figures_v22/ablation_bars.py",      "Ablation: 6-component ΔvsFull bars"),
    ("build_walltime",      "latex/figures_v22/build_walltime.py",     "Build wall-clock time bars"),
    ("cost_bars",           "latex/figures_v22/cost_bars.py",          "Per-query / total cost bars"),
    ("external_benchmarks", "latex/figures_v22/external_benchmarks.py","External 4 benchmarks (BGE-large)"),
    ("prelim_evolution",    "latex/figures_v22/prelim_evolution.py",   "Preliminary study evolution (v4 fail / v3xf converge)"),
    ("retrieval_stats",     "latex/figures_v22/retrieval_stats.py",    "Retrieval statistics"),
    ("token_breakdown",     "latex/figures_v22/token_breakdown.py",    "Token breakdown per stage"),
    ("token_efficiency",    "latex/figures_v22/token_efficiency.py",   "Token context-efficiency curve"),
    ("tradeoff_scale",      "latex/figures_v22/tradeoff_scale_code.py","Token tradeoff 10M+20M (aligned, savings 3.16-3.18x)"),
    ("external_comparison", "latex/figures_supp/external_comparison.py",     "Supp: external comparison"),
    ("locomo_category",     "latex/figures_supp/locomo_category.py",         "Supp: LoCoMo category breakdown"),
    ("oracle_2x2_lines",    "latex/figures_supp/oracle_2x2_lines.py",        "Supp: 2x2 oracle (lines)"),
    ("oracle_2x2_marginal", "latex/figures_supp/oracle_2x2_marginal.py",     "Supp: 2x2 oracle (marginal)"),
]

def run_one(name, relpath):
    script = os.path.join(HERE, relpath)
    if not os.path.exists(script):
        # fall back: some scripts may live directly under figures/ or figures_v22/
        alt = os.path.join(HERE, os.path.basename(os.path.dirname(relpath)), os.path.basename(relpath))
        script = alt if os.path.exists(alt) else script
    if not os.path.exists(script):
        print(f"  [SKIP] {name}: not found ({relpath})")
        return False
    cwd0 = os.getcwd()
    try:
        # run in the script's own directory so relative output paths match standalone behavior
        os.chdir(os.path.dirname(script))
        import matplotlib
        matplotlib.use("Agg")
        runpy.run_path(os.path.basename(script), run_name="__main__")
        print(f"  [OK]   {name}")
        return True
    except Exception:
        print(f"  [FAIL] {name}")
        traceback.print_exc()
        return False
    finally:
        os.chdir(cwd0)

def main():
    ap = argparse.ArgumentParser(description="Generate all paper data figures")
    ap.add_argument("--list", action="store_true", help="list figure sections")
    ap.add_argument("--only", nargs="*", help="only these sections (by name)")
    args = ap.parse_args()
    if args.list:
        for n, p, d in FIGS:
            print(f"{n:22s} {d}")
        return
    sel = FIGS if not args.only else [f for f in FIGS if f[0] in set(args.only)]
    print(f"Generating {len(sel)} figure section(s)...")
    ok = 0
    for n, p, d in sel:
        if run_one(n, p):
            ok += 1
    print(f"\nDone: {ok}/{len(sel)} succeeded.")
    print("README assets live under ../assets and are not regenerated by this script.")

if __name__ == "__main__":
    main()
